Import: Use the phpSpreadsheet library to import data from xls(x), ods, csv, html, etc.
Admidio/admidio pull request #1043
Opened 2021-05-11 10:10 UTC by kainhofer

Import: Use the phpSpreadsheet library to import data from xls(x), ods, csv, html, etc.

-) Allow choosing the import file type (auto-detect, xlsx, xls, ods, csv, html (and all other formats auto-detected by phpSpreadsheet))
-) Depending on the import file type, provide settings for the worksheet inside the spreadsheet, or the encoding, separator and enclosure of CSV-files (use javascript to show/hide and en/disable the unused settings for a format)
-) Use the phpSpreadsheet library to load all types of import file, using the settings selected by the user. The data will be available as an array, irrespective of the original import format
-) The actual import function is unchanged and simply uses the array now created by phpSpreadsheet (previously by parsing the CSV lines manually)

This implements parts 1, 2 and 4 of Issue #826

2021-05-12 07:18 UTC, Fasse commented
That looks like a good feature. I will review this at the weekend.

One thing that I saw in the files is about the translation string. You use for example `<string name="SYS_CSVIMPORT_SEP_AUTO">Auto-detect</string>` . We try to use the full english name within the name attribute so you better know in the code which text should be shown. Also the context information CSVIMPORT is not necessary because we want to use the same text also in other modules if it's useful there. So a better name for it would be `<string name="SYS_AUTO_DETECT">Auto-detect</string>`. 

The text SYS_CSVIMPORT_ENC_DQUOTE and some other should not be a translation string. It should be a preference or we set it fix in the code if we have no preference for it.

2021-05-14 15:41 UTC, kainhofer commented
I have now made the translatable field identifier more generic. The DQUOTE and QUOTE fields should be translatable, because it makes sense to add an explanation (which I did in my last commit), too.

2021-05-15 06:15 UTC, Fasse commented
I saw that you use composer for the external libs and therefore create the folder libs/server/vendor . Since the folder structure is very deep I think if we should add a vendor folder within the adm_program folder. e.g. `adm_program/vendor` instead of `adm_program/libs/server/vendor` or should it be something like `adm_program/vendor_server`

What do you think?

2021-05-15 21:22 UTC, Fasse requested changes

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="MEM_IMPORT_SHEETNOTEXISTS">The worksheet #VAR1# does not exist in the imported file!</string>
Better name MEM_IMPORT_SHEET_NOT_EXISTS

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_DQUOTE">"</string>
Duplicate see below.

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_QUOTE">'</string>
Duplicate see below

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_NOQUOTE">No quotation</string>
Better SYS_NO_QUOTATION

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_FIELDSEPARATOR">Separator for CSV-file</string>
Better name SYS_SEPARATOR_FOR_CSV_FILE

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_ENCODING_DEFAULT">Default encoding (UTF-8)</string>
Better SYS_DEFAULT_ENCODING_UTF8

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_FILE_XLSX">Excel 2007-365 (*.xlsx, *.xlsm, *.xlsb)</string>
SYS_EXCEL_2007_365

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_FILE_XLS">Excel 97-2003 (*.xls, *.xlm)</string>
SYS_EXCEL_97_2003

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_FILE_ODS">ODF Spreadsheet (*.ods)</string>
SYS_ODF_SPREADSHEET

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_FILE_CSV">Comma-/tab-separated file (*.csv)</string>
...name="SYS_COMMA_SEPARATED_FILE">Comma-separated file (*.csv)</string>

2021-05-15 21:22 UTC, Fasse commented on adm_program/languages/en.xml
> +  <string name="SYS_FILE_HTML">HTML table</string>
SYS_HTML_TABLE

2021-05-16 09:05 UTC, kainhofer commented
I have now properly renamed all translatable string identifiers per your convention and placed them in the corresponding (alphabetic) position in the language files. I have also squashed all commits into two (one purely for importing the phpSpreadsheet library and the other with the actual changes to admidio using the phpSpreadsheet library).

2021-05-17 09:03 UTC, Fasse requested changes
Ok, the code looks fine.

I found one thing when testing the new feature:
- explicit select csv file format
- select a csv file
- add a role to which the members should be added
- click "Weiter"

At the following page this error is shown: 
> Your requested sheet index: 1 is out of bounds. The actual number of sheets is 1.

2021-06-14 13:22 UTC, merged