update README.md
Admidio/admidio pull request #1505
Opened 2023-10-27 11:11 UTC by 0Armaan025

2023-10-27 15:23 UTC, Fasse requested changes

2023-10-27 15:23 UTC, Fasse commented on README.md
> +If you appreciate Admidio and our project, consider [making a donation](https://www
The text is truncated. Could you please complete the description.

2023-10-31 17:06 UTC, 0Armaan025 commented
Done please check

2023-11-02 20:55 UTC, Fasse requested changes

2023-11-02 20:55 UTC, Fasse commented on README.md
> +If you appreciate Admidio , consider donating please
Hmm, I'm not satisfied with this part. Maybe something like this:

> If you appreciate Admidio, consider making a [donation](https://www.admidio.org/donate.php).
> Thanks for contributing!

2023-11-02 20:56 UTC, Fasse commented
@0Armaan025 I would like to change the donating part. Please have a look.

2023-11-05 06:37 UTC, merged

2023-11-05 06:37 UTC, Fasse commented
@0Armaan025 Thanks for contributing :)